### Index
GET "http://localhost:3000/users.json"

### Show
GET "http://localhost:300/users/1.json"

### Create
POST "http://localhost:300/users.json"
Content-Type: application/json

{
  
}

### Update

### Destroy